### ISSUE TITLE
Values truncated in ui.nonpar

### ISSUE THREAD

**Issue by jwang-lilly** [HansLandsheer/UncertainInterval#11]
Hi, I encounter the following error message when running 
ua = ui.nonpar(ref, test)

Warning in check.data(ref, test, model = model) :
  Your test has less than 20 different values. The ordinal data model may be better applicable.

my ref is 0, 1 values
test data are like the following, they are continuous data of >800 data points.
0.691 1.297 0.779 0.998 0.587 0.198 0.521 0.652 0.291 1.402 0.374
0.748 0.413 1.102 0.621 0.553 0.289 0.504 0.526 0.909 1.300 0.272

I suspect the test values are truncated to make the data having only 20 different values.

@HansLandsheer, Any advice is greatly appreciated.

**Comment by jwang-lilly** [comment]
Closing this because I made an error resulting in the message.

**Comment by HansLandsheer** [comment]
Thank you for using UncertainInterval. 

If you think that your error is easily made, please inform me about it in more detail.
